# Generated by Django 4.1 on 2022-11-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PENGUNJUNG', 'Pengunjung'), ('DOKTER', 'Dokter'), ('PASIEN', 'Pasien')], max_length=50, null=True),
        ),
    ]
