# Generated by Django 4.1 on 2022-11-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login.user',),
        ),
    ]
