# Generated by Django 4.1 on 2022-11-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_pasienprofile_dokterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
