# Generated by Django 4.1.1 on 2022-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wallofhope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=38, null=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
