# Generated by Django 4.1 on 2022-10-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallofhope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallofhope',
            name='deskripsi',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallofhope',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='wallofhope',
            name='judul',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
