# Generated by Django 4.1 on 2022-10-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallofhope', '0002_alter_wallofhope_deskripsi_alter_wallofhope_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallofhope',
            name='image',
            field=models.ImageField(upload_to='wallofhope/image'),
        ),
    ]
