# Generated by Django 4.1 on 2022-10-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallofhope', '0003_alter_wallofhope_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallofhope',
            name='image',
            field=models.URLField(),
        ),
    ]
