# Generated by Django 4.1 on 2022-10-31 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallofhope', '0004_alter_wallofhope_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallofhope',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallofhope',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
