# Generated by Django 4.1 on 2022-10-30 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='id',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=models.TextField(help_text='Write content here'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='title',
            field=models.CharField(error_messages={'unique': 'Article with this Title already exists.'}, help_text='Required. Must be unique.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
