# Generated by Django 4.1 on 2022-10-27 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
