# Generated by Django 4.1 on 2022-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlepage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
