# Generated by Django 4.1 on 2022-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlepage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='title',
            field=models.CharField(error_messages={'unique': 'Person with this FirstName already exists.'}, max_length=255, unique=True),
        ),
    ]
