# Generated by Django 4.1 on 2022-10-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articlepage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
