# Generated by Django 4.1 on 2022-11-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
