# Generated by Django 4.1 on 2022-11-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_data_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
